In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.random.seed(50)

In [ ]:
p_binary = np.random.uniform(size=10)
p_multi = np.random.uniform(size=(10,3)) #3 classes com 10 valores

y_binary = (np.random.uniform(size=10) > 0.5).astype(int)
y_binary
y_multi = np.random.uniform(size=(10,3)).argmax(axis=1)#coluna onde está o maior valor. Sò para ter uma classe

p_binary_threshold = (p_bynary > 0.4).astype(int)
p_multi_argmax = p_multi.argmax(axis=1)


In [ ]:
y_multi

array([1, 2, 0, 0, 1, 2, 1, 1, 1, 1])

### ACURÁCIA

*não usar oficialmente, só para testar

*inadequada para dados desiquilibrados

*não diz muita coisa, apenas o quanto acerta



In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("PREVISÃO = {}\nY = {}".format(p_binary_threshold, y_binary))

P = [1 1 1 1 1 0 1 1 1 0]
Y = [0 1 0 1 0 0 1 0 1 1]


In [ ]:
accuracy_score(y_binary, p_binary_threshold)

0.5

## PRECISION

*dos casos previsto como positivos, quantos realmentes são positivos

*Ex: quantas pessoas realmente irão comprar

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
print("P = {}\nY = {}".format(p_binary_threshold, y_binary))
precision_score(y_binary, p_binary_threshold)

P = [1 1 1 1 1 0 1 1 1 0]
Y = [0 1 0 1 0 0 1 0 1 1]


0.5

só pega os casos acertados. Exemplo: se tem 3 casos que foi previsto 1, quantos acertou, foi 2. Logo, foi 66%

# RECALL
*É MAIS IMPORTANTE DETECTAR TODOS OS POSITIVOS DO QUE ACERTAR QUEM REALMENTE É POSITIVO? USA ELE -> MAIS PROCESSAMENTO

*dos que eram realmente positivos, para uma classe, quantas eu detectei como positivas?

*taxa de detecção

Ex: se eu quero que 10  pessoas vão para uma live entre 1000 pessoas, ela vai detectar. É mais importante detectar os positivos do que acertar quem são os positivos

In [ ]:
from sklearn.metrics import recall_score
print("PREVISÃO = {}\nY = {}".format(p_binary_threshold, y_binary))
recall_score(y_binary, p_binary_threshold)

PREVISÃO = [1 1 1 1 1 0 1 1 1 0]
Y = [0 1 0 1 0 0 1 0 1 1]


0.8

In [ ]:
#tem 5 positivos(y), dos quais 4 acertou

# F1 SCORE

-média harmônica entre os precision e recall:

( 2 *precision * recall) / (precision + recal)

- quanto não tem preferência entre precision e recall

-Trabalha bem quando os dados tem classe desproporcionais (grande número de dados negativos reais)

-indica a qualidade geral do seu model



In [ ]:
from sklearn.metrics import f1_score
print("PREVISÃO = {}\nY = {}".format(p_binary_threshold, y_binary))
f1_score(y_binary, p_binary_threshold)

PREVISÃO = [1 1 1 1 1 0 1 1 1 0]
Y = [0 1 0 1 0 0 1 0 1 1]


0.6153846153846154

# KAPPA

-Se a concordância foi por aleatoriedade

-Mede a cordância medida pela aleatoriedade de acertar o valor

-A estatística kappa, que é um número entre -1 e 1. O valor máximo significa concordância completa; zero ou menos significa acordo de chance.

In [ ]:
from sklearn.metrics import cohen_kappa_score
print("PREVISÃO = {}\nY = {}".format(p_binary_threshold, y_binary))
cohen_kappa_score(y_binary, p_binary_threshold)

PREVISÃO = [1 1 1 1 1 0 1 1 1 0]
Y = [0 1 0 1 0 0 1 0 1 1]


0.0

# AVALIA A PROBABILIDADE DIRETAMENTE SEM PONTO DE CORTE
*mol.predict_proba

# Log LOss

Proporção que o evento ocorre na vida real

Ex:
se o time A jogar contra o time B, e tiver 50% de ganhar, se jogarem 10 vezes, 5 vezes o time A vai ganhar
-A log loss estará na mínima quando o modelo prever 0.5 (50% de ganhar)

In [ ]:
from sklearn.metrics import log_loss
print("PREVISÃO = {}\nY = {}".format(p_binary, y_binary))
log_loss(y_binary, p_binary)

PREVISÃO = [1 1 1 1 1 0 1 1 1 0]
Y = [1 0 1 1 1 1 0 0 0 0]


0.8072972567004862

In [ ]:
#assim, quanto maior for o valor dos 50% de ganhar, pior está o modelo
#QUANTO MENOR, MELHOR
#USA PARA QUANDO PRECISAR PROBABILIDADES BEM CALIBRADAS. eX: BOLSA DE VALORES

#ROC AUC

-Qual a chance de um exemplo positivo ter uma previsão maior do que um positivo

-AUC é bom para problemas de classificação com desequilíbrio de classe

-é bom quando garantir que positivos sejam rankeados acima dos negativos é mais importante do que prever a probabilidade real do evento

(quando os positivos são mais imporatntes que a probabilidade real)

Ex: em vez de saber exatamente quando um email é spam, ordena os primeiros com a maior probabilidade de ser spam.

In [ ]:
from sklearn.metrics import roc_auc_score
print("PREVISÃO = {}\nY = {}".format(p_binary, y_binary))
roc_auc_score(y_binary, p_binary)

PREVISÃO = [0.98247623 0.52243872 0.53917851 0.94702819 0.15318816 0.2801585
 0.62494318 0.30397067 0.83573299 0.29270279]
Y = [1 0 1 1 1 1 0 0 0 0]


0.52

In [ ]:
#valor abaixo de 0.5, quer dizer que o modelo está pior do que fosse aleatório
#É PRECISO QUE O AUC ESJA MAIOR QUE 0.5


In [ ]:
#PERCEBE-SE QUE DÁ PRATICAMENTE O MESMO VALOR DO ROC AUC, OU SEJA, ESSA É UMA FORMA DE FAZER
sum_over = 0
total = 10000
for i in range(total):
  caixa_de_positivos = p_binary[y_binary == 1] #pega os elementos do p_binary quando o valor do y_binary for 1, no mesmo índice
  caixa_de_negativos = p_binary[y_binary == 0]

  positivo = np.random.choice(caixa_de_positivos, size = 1, replace=False)
  negativo = np.random.choice(caixa_de_negativos, size = 1, replace=False)

  if positivo > negativo:
    sum_over +=1
sum_over/total




0.5257

In [ ]:
p_binary


array([0.98247623, 0.52243872, 0.53917851, 0.94702819, 0.15318816,
       0.2801585 , 0.62494318, 0.30397067, 0.83573299, 0.29270279])

In [ ]:
caixa_de_positivos

array([0.98247623, 0.53917851, 0.94702819, 0.15318816, 0.2801585 ])

In [ ]:
y_binary

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0])

#AUPRC

-média ponderada da curva entre precisoin e recall

-quanto maior melhor

In [ ]:
from sklearn.metrics import average_precision_score
print("PREVISÃO = {}\nY = {}".format(p_binary, y_binary))
average_precision_score(y_binary, p_binary)

PREVISÃO = [0.98247623 0.52243872 0.53917851 0.94702819 0.15318816 0.2801585
 0.62494318 0.30397067 0.83573299 0.29270279]
Y = [1 0 1 1 1 1 0 0 0 0]


0.7088888888888889

OUTRA COISA

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_multi, p_multi_argmax))


              precision    recall  f1-score   support

           0       0.50      0.25      0.33         4
           1       0.50      1.00      0.67         3
           2       0.00      0.00      0.00         3

    accuracy                           0.40        10
   macro avg       0.33      0.42      0.33        10
weighted avg       0.35      0.40      0.33        10

